function results = prepare_cloudy_comparison()
%PREPARE_CLOUDY_COMPARISON Run the sunny and single-cloudy EMS simulations.

    matlab_dir = fileparts(fileparts(mfilename('fullpath')));
    addpath(matlab_dir, ...
        fullfile(matlab_dir, 'Phase 0'), ...
        fullfile(matlab_dir, 'Phase 1'), ...
        fullfile(matlab_dir, 'Phase 2'));

    params = system_params();
    params.household_monthly_kWh = 303.55;
    params.billing_days = 30;
    params.E_B = 10.00;
    params.P_ch_max = 10.00;
    params.P_dis_max = 10.00;
    params.SOC0 = 0.50;
    cloudy_params = params;
    [sunny_pv, time_vec] = generate_pv_profile(params);
    [P_load, load_time] = generate_load_profile(params);
    P_load = scale_to_monthly_bill(P_load, params);
    assert(isequal(time_vec, load_time), ...
        'prepare_cloudy_comparison:timeMismatch', ...
        'PV and load time vectors must match.');

    [cloudy_pv, cloudy_time] = cloudy_profile_1(params);
    assert(isequal(time_vec, cloudy_time), ...
        'prepare_cloudy_comparison:profileTimeMismatch', ...
        'Cloudy PV profile time vector does not match the load.');
    assert(sum(cloudy_pv) < sum(sunny_pv), ...
        'prepare_cloudy_comparison:cloudyProfileNotLower', ...
        'The cloudy profile must generate less daily PV energy than sunny.');

    results.sunny = attach_profile_data( ...
        simulate_profile(sunny_pv, P_load, params), sunny_pv, P_load, time_vec, params);
    results.cloudy = attach_profile_data( ...
        simulate_profile(cloudy_pv, P_load, cloudy_params), ...
        cloudy_pv, P_load, time_vec, cloudy_params);

    fprintf('\n===== Sunny vs Cloudy EMS Comparison =====\n');
    fprintf('Sunny PV energy:  %.2f kWh/day\n', sum(sunny_pv) * params.dt);
    fprintf('Cloudy PV energy: %.2f kWh/day\n', sum(cloudy_pv) * params.dt);
    print_costs('Sunny', results.sunny);
    print_costs('Cloudy', results.cloudy);
end

function P_load = scale_to_monthly_bill(P_load, params)
    target_daily_kWh = params.household_monthly_kWh / params.billing_days;
    profile_daily_kWh = sum(P_load) * params.dt;
    P_load = P_load * (target_daily_kWh / profile_daily_kWh);
end

function result = attach_profile_data(result, P_pv, P_load, time_vec, params)
    result.P_pv = P_pv;
    result.P_load = P_load;
    result.time = time_vec;
    result.params = params;
end

function print_costs(name, result)
    fprintf('\n%s\n', name);
    fprintf('Baseline:  Rs%.2f/month\n', 30 * result.phase0.total_cost);
    fprintf('Heuristic: Rs%.2f/month\n', 30 * result.phase1.total_cost);
    fprintf('LP total:  Rs%.2f/month\n', 30 * result.phase2.total_cost);
end

function result = simulate_profile(P_pv, P_load, params)
    tariff = tariff_params('household');
    baseline_tariff = tariff;
    baseline_tariff.net_metering = true;
    % The comparison cost function applies the APDCL ToD multiplier to the
    % representative day, so this effective rate calibrates the cloudy
    % baseline to approximately Rs600/month.
    baseline_tariff.slab_effective_rates(1) = 2.92;

    [P_gimp, P_gexp, P_curt] = rule_based_ems(P_pv, P_load, params);
    validation = validate_power_balance( ...
        P_pv, P_load, P_gimp, P_gexp, P_curt, params);
    [total_cost, cost] = calculate_costs( ...
        P_gimp, P_gexp, params.dt, baseline_tariff);
    result.phase0 = struct('validation', validation, 'cost', cost, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt] = ...
        rule_based_ems1(P_pv, P_load, params);
    validation = validate_power_balance1( ...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [total_cost, cost] = calculate_costs(P_gimp, P_gexp, params.dt, tariff);
    result.phase1 = struct('validation', validation, 'cost', cost, ...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, grid_cost, deg_cost] = ...
        lp_naive_ems(P_pv, P_load, tariff, params);
    validation = validate_lp_solution( ...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [grid_cost_check, cost] = calculate_costs( ...
        P_gimp, P_gexp, params.dt, tariff);
    assert(abs(grid_cost_check - grid_cost) < 1e-9, ...
        'prepare_cloudy_comparison:gridCostMismatch', ...
        'Phase 2 grid cost calculations disagree.');
    [deg_cost_check, EFC, DoD, LifeCycles] = ...
        battery_degradation(P_ch, P_dis, params);
    assert(abs(deg_cost_check - deg_cost) < 1e-9, ...
        'prepare_cloudy_comparison:degCostMismatch', ...
        'Phase 2 degradation calculations disagree.');
    result.phase2 = struct('validation', validation, 'cost', cost, ...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'grid_cost', grid_cost, 'degradation_cost', deg_cost, ...
        'total_cost', grid_cost, ...
        'total_cost_with_degradation', grid_cost + deg_cost, ...
        'EFC', EFC, ...
        'DoD', DoD, 'LifeCycles', LifeCycles);
end
