    function results = run_all_phases()
%RUN_ALL_PHASES Run and compare the Phase 0, Phase 1, and Phase 2 EMS runs.
%
%   This orchestration function keeps the individual main_phase*.m drivers
%   unchanged. It calls the same shared profile, dispatch, validation, and
%   cost functions used by those drivers, then plots a cost comparison.
%
%   RESULTS contains the dispatch outputs, validation reports, and cost
%   summaries for each phase.

    matlab_dir = fileparts(mfilename('fullpath'));
    addpath(matlab_dir, ...
        fullfile(matlab_dir, 'Phase 0'), ...
        fullfile(matlab_dir, 'Phase 1'), ...
        fullfile(matlab_dir, 'Phase 2'));

    %% Shared inputs
    params = system_params();
    [P_pv, time_vec] = generate_pv_profile(params);
    [P_load, time_vec_load] = generate_load_profile(params);
    assert(isequal(time_vec, time_vec_load), ...
        'run_all_phases:timeMismatch', 'PV and load time vectors must match.');

    %% Phase 0: no-storage baseline
    [P_gimp, P_gexp, P_curt] = rule_based_ems(P_pv, P_load, params);
    validation = validate_power_balance(...
        P_pv, P_load, P_gimp, P_gexp, P_curt, params);
    [total_cost, cost] = calculate_costs(P_gimp, P_gexp, params.dt);

    results.phase0 = struct(...
        'P_gimp', P_gimp, 'P_gexp', P_gexp, 'P_curt', P_curt, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    %% Phase 1: rule-based battery EMS
    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt] = ...
        rule_based_ems1(P_pv, P_load, params);
    validation = validate_power_balance1(...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [total_cost, cost] = calculate_costs(P_gimp, P_gexp, params.dt);

    results.phase1 = struct(...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    %% Phase 2: LP-based EMS with post-hoc degradation analysis
    tariff = tariff_params();
    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, grid_cost, deg_cost] = ...
        lp_naive_ems(P_pv, P_load, tariff, params);
    validation = validate_lp_solution(...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [deg_cost_check, EFC, DoD, LifeCycles] = ...
        battery_degradation(P_ch, P_dis, params);
    assert(abs(deg_cost_check - deg_cost) < 1e-9, ...
        'run_all_phases:degCostMismatch', ...
        'Phase 2 degradation cost calculations disagree.');
    [grid_cost_check, cost] = calculate_costs(P_gimp, P_gexp, params.dt);
    assert(abs(grid_cost_check - grid_cost) < 1e-9, ...
        'run_all_phases:gridCostMismatch', ...
        'Phase 2 grid cost calculations disagree.');

    results.phase2 = struct(...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', grid_cost, 'degradation_cost', deg_cost, ...
        'total_cost', grid_cost + deg_cost, 'EFC', EFC, ...
        'DoD', DoD, 'LifeCycles', LifeCycles);

    results.params = params;
    results.P_pv = P_pv;
    results.P_load = P_load;
    results.time = time_vec;

    %% Console comparison
    phase_names = {'Phase 0', 'Phase 1', 'Phase 2'};
    grid_costs = [results.phase0.grid_cost, results.phase1.grid_cost, ...
        results.phase2.grid_cost];
    degradation_costs = [results.phase0.degradation_cost, ...
        results.phase1.degradation_cost, results.phase2.degradation_cost];
    total_costs = grid_costs + degradation_costs;
    monthly_total_costs = 30 * total_costs;

    fprintf('\n===== All-Phase Cost Comparison =====\n');
    fprintf('%-12s %15s %18s %15s %18s\n', ...
        'Phase', 'Grid/day (Rs)', 'Degradation/day (Rs)', ...
        'Total/day (Rs)', 'Total/month (Rs)');
    for phase_index = 1:numel(phase_names)
        fprintf('%-12s %15.2f %18.2f %15.2f %18.2f\n', phase_names{phase_index}, ...
            grid_costs(phase_index), degradation_costs(phase_index), ...
            total_costs(phase_index), monthly_total_costs(phase_index));
    end
    fprintf('=====================================\n');

    %% Cost comparison plot
    figure('Name', 'All-Phase EMS Cost Comparison', ...
        'Position', [150, 150, 900, 600]);
    subplot(2, 1, 1);
    bar([grid_costs; degradation_costs].', 'stacked');
    grid on;
    set(gca, 'XTick', 1:numel(phase_names), 'XTickLabel', phase_names);
    ylabel('Cost [Rs]');
    title('Daily Cost Components');
    legend('Grid cost', 'Post-hoc degradation cost', 'Location', 'northwest');

    subplot(2, 1, 2);
    bar(monthly_total_costs);
    grid on;
    set(gca, 'XTick', 1:numel(phase_names), 'XTickLabel', phase_names);
    ylabel('Cost [Rs]');
    title('30-Day Equivalent Household Bill');
    sgtitle('Phase 0 vs. Phase 1 vs. Phase 2');
end