function results = simulate_day(P_pv, P_load, params)
%SIMULATE_DAY Run all 3 EMS controllers on a given PV/load profile.
%   results = simulate_day(P_pv, P_load, params) runs Phase 0 (baseline),
%   Phase 1 (rule-based), and Phase 2 (LP-based) controllers on the given
%   profiles and returns a struct with phase0, phase1, phase2 results.
%
%   This is the single source of truth for the simulation pipeline.
%   Callers are responsible for attaching profile data (P_pv, P_load, time)
%   and any presentation-level adjustments.
%
%   See also: run_all_phases, prepare_cloudy_comparison.

    tariff = tariff_params();

    %% Phase 0: no-storage baseline
    [P_gimp, P_gexp, P_curt] = rule_based_ems_p0(P_pv, P_load, params);
    validation = validate_power_balance_p0( ...
        P_pv, P_load, P_gimp, P_gexp, P_curt, params);
    [total_cost, cost] = calculate_costs(P_gimp, P_gexp, params.dt);

    results.phase0 = struct( ...
        'P_gimp', P_gimp, 'P_gexp', P_gexp, 'P_curt', P_curt, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    %% Phase 1: rule-based battery EMS
    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt] = ...
        rule_based_ems_p1(P_pv, P_load, params);
    validation = validate_power_balance_p1( ...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [total_cost, cost] = calculate_costs(P_gimp, P_gexp, params.dt);

    results.phase1 = struct( ...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', total_cost, 'degradation_cost', 0, ...
        'total_cost', total_cost);

    %% Phase 2: LP-based EMS with post-hoc degradation analysis
    [P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, grid_cost, deg_cost] = ...
        lp_naive_ems(P_pv, P_load, tariff, params);
    validation = validate_lp_solution( ...
        P_pv, P_load, P_ch, P_dis, P_gimp, P_gexp, SOC, P_curt, params);
    [deg_cost_check, EFC, DoD, LifeCycles] = ...
        battery_degradation(P_ch, P_dis, params);
    assert(abs(deg_cost_check - deg_cost) < 1e-9, ...
        'simulate_day:degCostMismatch', ...
        'Phase 2 degradation cost calculations disagree.');
    [grid_cost_check, cost] = calculate_costs(P_gimp, P_gexp, params.dt);
    assert(abs(grid_cost_check - grid_cost) < 1e-9, ...
        'simulate_day:gridCostMismatch', ...
        'Phase 2 grid cost calculations disagree.');

    results.phase2 = struct( ...
        'P_ch', P_ch, 'P_dis', P_dis, 'P_gimp', P_gimp, ...
        'P_gexp', P_gexp, 'P_curt', P_curt, 'SOC', SOC, ...
        'validation', validation, 'cost', cost, ...
        'grid_cost', grid_cost, 'degradation_cost', deg_cost, ...
        'total_cost', grid_cost + deg_cost, 'EFC', EFC, ...
        'DoD', DoD, 'LifeCycles', LifeCycles);
end
